apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-cpu-load-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: keda-consumer-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: "Utilization"
      value: "80"  # Scale up when CPU usage exceeds 80%
