apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map.yaml
  - sqs-secret.yaml
  - sqs-trigger-authentication.yaml
  - consumer-deployment.yaml
  - producer-deployment.yaml
  - keda-scaledobject-sqs.yaml